import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from '@/app/context/cartContext';
import { RemovedItemsProvider } from '@/app/context/removedItemsContext';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RemovedItemsProvider>
          <CartProvider>
            <ToastContainer position="top-right" autoClose={3000} />
            {children}
          </CartProvider>
        </RemovedItemsProvider>
      </body>
    </html>
  );
}
