import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from '@/app/context/cartContext';
import { WalletProvider } from '../app/context/walletContext';
import { RemovedItemsProvider } from '@/app/context/removedItemsContext';
import { TransactionsProvider } from '@/app/context/transactionsContext';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Picture Shop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransactionsProvider>
          <RemovedItemsProvider>
            <WalletProvider>
              <CartProvider>
                <ToastContainer position="top-right" autoClose={3000} />
                <Navbar />
                {children}
                <Footer />
              </CartProvider>
            </WalletProvider>
          </RemovedItemsProvider>
        </TransactionsProvider>
      </body>
    </html>
  );
}
